os: linux
dist: xenial

language: java

jdk:
  - openjdk11

notifications:
  email:
    - developers@diribet.cz

cache:
  directories:
    - $HOME/.m2

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --batch; fi

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: diribet/aqdef-tools
      branch: master
      jdk: openjdk11
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: diribet/aqdef-tools
      tags: true
      jdk: openjdk11