name: Publish

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  publics:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Deploy snapshot
        run: mvn deploy -B

      - name: Deploy release
        if: github.ref_type == 'tag'
        run: mvn deploy -Drevison=${{ github.ref_name }} -Prelease -B