name: Test report

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: Tests                       # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results